### Schema
DROP DATABASE IF EXISTS chalkboardplus_db;
CREATE DATABASE chalkboardplus_db;
USE chalkboardplus_db;

CREATE TABLE user
(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    sex VARCHAR(255) NOT NULL,
    assignment VARCHAR(255) NOT NULL,
    dailygrade VARCHAR(255),
    quizgrade VARCHAR(255),
    testgrade VARCHAR(255),
    address VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    photo VARCHAR(255),
	PRIMARY KEY (id)
);


CREATE TABLE groupe
(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT(11) UNSIGNED NOT NULL,
	short_slug VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE attendance
(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	attcode_id INT(11) NOT NULL,
    user_id INT(11) NOT NULL,	
    PRIMARY KEY (id)
);

CREATE TABLE att_code
(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    slug VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE post
(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT(11) NOT NULL,
    content VARCHAR(255) NOT NULL,
    attachment VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE department
(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT(11) UNSIGNED NOT NULL,
    dept_name VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE class
(
	id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	class_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    user_id INT(1) UNSIGNED NOT NULL,
    dept_id INT(11) UNSIGNED,
	PRIMARY KEY (id)
);
